services:
  db:
    container_name: postgres_sezer
    image: postgres
    environment:
      POSTGRES_USER: bughorizon_sezer
      POSTGRES_PASSWORD: bughorizon123
      PGDATA: /data/postgres
      POSTGRES_DB: bughorizon
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d bughorizon" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db: